stages:
  - check
  - build
  - test
  - publish

include:
  # Check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest
  - component: $CI_SERVER_FQDN/eng/toolchain/rust/rust-ci/check-commits@main
  - component: $CI_SERVER_FQDN/eng/toolchain/rust/rust-ci/run-clippy-fmt@main
    inputs:
      job-name: clippy-fmt:zynqmp
      anod_install_options: --target=aarch64-elf
      anod_printenv_options: --target=aarch64-elf
      clippy_options: --all-targets --no-deps --manifest-path zynqmp/Cargo.toml --target aarch64-unknown-none
  - component: $CI_SERVER_FQDN/eng/toolchain/rust/rust-ci/run-clippy-fmt@main
    inputs:
      job-name: clippy-fmt:xtask
      clippy_options: --all-targets --no-deps --manifest-path xtask/Cargo.toml

  # Build
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      anod-args: run build

  # Test
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      anod-args: run test
      needs: []

# Publish
publish:
  stage: publish
  services:
    - image:pe-base
    - security_group:GitLabRunnerTasksExecPrivilegedSG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - generic_anod_ci --setup wave --no-current-project
    - . /tmp/ci_env.sh
    - anod build --target aarch64-elf rust-multi
    - eval `anod printenv --target aarch64-elf rust-multi`
    - cd zynqmp && cargo publish
  environment:
    name: "crates.io"
    action: start
